# CI on Windows via appveyor

environment:
  matrix:
    - PYTHON: "C:\\Python37-conda64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_ENV: "py37"

install: true
build: true
test_script: true
