channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - alabaster=0.7.12
  - apipkg=1.5
  - appdirs=1.4.4
  - attrs=20.3.0
  - babel=2.8.1
  - black=19.10b0
  - blas=1.0
  - bokeh=2.2.3
  - bzip2=1.0.8
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - cftime=1.2.1
  - chardet=3.0.4
  - check-manifest=0.45
  - click=7.1.2
  - cloudpickle=1.6.0
  - conda=4.8.3
  - conda-package-handling=1.6.1
  - coverage=5.3
  - cryptography=2.9.2
  - curl=7.69.1
  - cytoolz=0.11.0
  - dask=2.30.0
  - dask-core=2.30.0
  - distributed=2.30.1
  - docutils=0.16
  - eccodes=2.19.0
  - execnet=1.7.1
  - freetype=2.10.4
  - fsspec=0.8.3
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - idna=2.9
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - jasper=1.900.1
  - jinja2=2.11.2
  - jpeg=9d
  - krb5=1.17.1
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libaec=1.0.4
  - libcurl=7.69.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - locket=0.2.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.6.0
  - msgpack-python=1.0.0
  - mypy_extensions=0.4.3
  - ncurses=6.2
  - netcdf4=1.5.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.3
  - partd=1.1.0
  - pathspec=0.7.0
  - pep517=0.9.1
  - pillow=8.0.1
  - pip=20.2.4
  - pluggy=0.13.1
  - psutil=5.7.2
  - py=1.9.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pyflakes=2.2.0
  - pygments=2.7.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.1.1
  - pytest-cache=1.0
  - pytest-cov=2.10.1
  - pytest-flakes=4.0.2
  - python=3.8.3
  - python-build=0.1.0
  - python-dateutil=2.8.1
  - python-eccodes=2020.10.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - regex=2020.10.15
  - requests=2.23.0
  - ruamel_yaml=0.15.87
  - scipy=1.5.2
  - setuptools=46.4.0
  - six=1.14.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.2.2
  - sphinx=3.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.31.1
  - tblib=1.7.0
  - tk=8.6.8
  - toml=0.10.1
  - toolz=0.11.1
  - tornado=6.0.4
  - tqdm=4.46.0
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - urllib3=1.25.8
  - wheel=0.34.2
  - xarray=0.16.1
  - xz=5.2.5
  - yaml=0.1.7
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
