[tool.black]
line-length = 99

[tool.pytest.ini_options]
norecursedirs = [
    "build",
    "docs",
    ".tox",
]
filterwarnings = ["ignore::FutureWarning"]

[tool.coverage.run]
branch = true
omit = ["setup.py"]
