name: weekly

on:
  push:
  schedule:
    - cron:  '0 9 * * 1'
  workflow_dispatch:

jobs:
  environment:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu]
        python: [3.6, 3.7, 3.8, 3.9]
        include:
          - os: macos
            python: 3.8
          - os: windows
            python: 3.7
          - os: ubuntu
            python: 3.8
            extras: -minimal

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
        activate-environment: ${{ matrix.os }}-${{ matrix.python }}${{ extras }}
        environment-file: environment${{ extras }}.in.yml
    - name: Export concrete dependencies
      shell: bash -l {0}
      run: |
        conda env export --no-build -f tests/environment-${{ matrix.os }}-${{ matrix.python }}${{ extras }}.yml
        git diff
    - name: Archive environment-${{ matrix.os }}-${{ matrix.python }}${{ extras }}.yml
      uses: actions/upload-artifact@v2
      with:
        name: environment-${{ matrix.os }}-${{ matrix.python }}${{ extras }}.yml
        path: tests/environment-${{ matrix.os }}-${{ matrix.python }}${{ extras }}.yml
